### ISSUE TITLE
misspelled module name, or incorrect module path?

### ISSUE THREAD

**Issue by pchapman869** [oravirt/ansible-oracle#146]
Hi, I've just pulled the latest vbox-rac respository and am getting this below.

vagrant 2.2.2 (changes to compat 2.0 during run)
ansible 2.5.1
trying ora 12.1.0.2 with oravirt/ol72

==> racnode-dc1-1: Running provisioner: ansible_local...
Vagrant has automatically selected the compatibility mode '2.0'
according to the Ansible version installed (2.2.1.0).

Alternatively, the compatibility mode can be specified in your Vagrantfile:
https://www.vagrantup.com/docs/provisioning/ansible_common.html#compatibility_mode

    racnode-dc1-1: Running ansible-playbook...
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/vagrant/extra-provision/ansible-oracle/roles/oraswgi-install/tasks/main.yml': line 52, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  - include_tasks: "{{ www_download_bin }}.yml"
    ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

I looked at extra-provision/ansible-oracle/roles/oraswgi-install/tasks/main.yml
and the only thing I could see was a previous lines where owner uses " " but group does not.

**Comment by pchapman869** [comment]
Urrggh, this is a bit of pain!
Using pip I tried ansible 2.4, then  2.5.3 as it has better include_tasks support.  Same error.
Tried putting compatibility_mode  in the Vagrantfile but it didn't make a diff. Don't know where it's getting the ansible version 2.2.1.0 !

**Comment by oravirt** [comment]
Ok - so this is because that vagrant box (`ol72`) is old (haven't been updated for ~2 years), and is running an older version of Ansible (2.2) which doesn't recognize some of the newer modules in Ansible I started using in the `ansible-oracle` repo.
If I get the time, I'll update the vagrant box. In the meantime (if you really need the ol72 box) you can do this:
1. `vagrant ssh racnode-dc1-1`
2.  `sudo yum update ansible -y`
3. `exit`
4. do the same for the other vm(s)
5. `git pull `(just pushed a minor change to the base-provision role)
6. `setup=true vagrant provision`

**Comment by oravirt** [comment]
I've updated the Vagrant box (`v20190109`), so that should take care of this issue.

**Comment by pchapman869** [comment]
Thanks so much Mikael !  I would have been happy to try a newer vagrant box.

**Comment by pchapman869** [comment]
still learning this!
