### ISSUE TITLE
database with db_domain

### ISSUE THREAD

**Issue by stelb** [oravirt/ansible-oracle#179]
Hi,

is there any way to create a database with db_domain?

db_name: TEST.test.customer

does not work

Regards

Stefan

**Comment by Rendanic** [comment]
I did not tested a configuration with db_domain. I think that ansible-oracle doesn't support this at the moment, because the db_domain has an effect on a lot of other tasks with connections using the service_name which without a domain..
Addind an init.ora parameter service_names with a service_name with and without a domain could be a work arround for this issue.

This is not an answer for how to configure the db_domain during database creation.

**Comment by stelb** [comment]
Ok, thanks for the answer and possible workaround. I tried a few things and thought I might be to stupid to find the solution ;)

I changed the db_domain manually right now as a quick solution, but then I am not able to manage it afterwards :/
