### ISSUE TITLE
While applying grid patches observed the below error.

### ISSUE THREAD

**Issue by jamespackiam** [oravirt/ansible-oracle#222]
Hi Everyone,

I am unable to resolve this error while running the playbook and not sure where this group_names needs to be defined. Please help where this variable needs to be defined.

PLAYBOOK: gi-opatch.yml ************************************************************************************************************************************************
1 plays in gi-opatch.yml
ERROR! The field 'hosts' has an invalid value, which includes an undefined variable. The error was: 'group_names' is undefined

The error appears to be in '/home/ansible/ansible-patching/gi-opatch.yml': line 1, column 4, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

 - name: Apply patches to GI
   ^ here

**Comment by Rendanic** [comment]
Needs a refactoring of current inventory and playbooks.
This is planned for a later time.

**Comment by Rendanic** [comment]
The example inventory from ansible-oracle does not have an example with patching.
Oracle changed the policy for downloading patches from support.oracle.com. Patches older then 1 year require a special password, which is changed every week.
The reason is: Customer should not install old patches.

I have to change the example inventory in short intervals and we need a download mechanism for download + unzip of RUs.
This is to difficult at the moment. That's why `ansible-oracle` has no patching in the example Inventory at the moment.

Please use the extended example from `ansible-oracle-inventory`.
https://github.com/opitzconsulting/ansible-oracle-inventory
