### ISSUE TITLE
oraswdb-install: missing oraInventory path

### ISSUE THREAD

**Issue by aetile** [oravirt/ansible-oracle#40]
Hello,

When running an 11.2.0.4 SW install with minimal specs I have this error at SW response file creation:

TASK [oraswdb-install : Setup response file for install (DB)] ****************************************************
failed: [ansible-node1] (item=[{u'state': u'present', u'oracle_init_params': u'', u'oracle_db_password': u'oracle', u'oracle_db_type': u'SI', u'service_name': u'test11g', u'oracle_db_name': u'test11g', u'listener_name': u'LISTENER', u'redolog_size_in_mb': 100, u'storage_type': u'FS', u'oracle_edition': u'SE', u'oracle_db_mem_totalmb': 1024, u'oracle_database_type': u'MULTIPURPOSE', u'home': u'db1', u'oracle_version_db': u'11.2.0.4'}, {'_ansible_parsed': True, 'stderr_lines': [u'grep: /u01/app/oraInventory/ContentsXML/inventory.xml: No such file or directory']

When I checked the box indeed the /u01/app/oraInventory directory did not exist.

**Comment by aetile** [comment]
The default value for this variable is set to oracle_inventory_loc: /u01/app/oraInventory

Either you need to create the directory or change the default value.

**Comment by aetile** [comment]
Check this in oraswdb-install/tasks/main.yml:

 name: Check if DB-server is already installed
    shell: grep "{{ oracle_home_db  }}" "{{ oracle_inventory_loc }}/ContentsXML/inventory.xml" |wc -l
    with_items: "{{oracle_databases}}"
    tags:
    - checkifdbinstall
    register: checkdbswinstall

**Comment by aetile** [comment]
After creating inventory location the check if already installed gives a correct return code:

TASK [oraswdb-install : Setup response file for install (DB)] ***************************************************************
failed: [ansible-node1] (item=[{u'state': u'present', u'oracle_init_params': u'', u'oracle_db_password': u'oracle', u'oracle_db_type': u'SI', u'service_name': u'test11g', u'oracle_db_name': u'test11g', u'listener_name': u'LISTENER', u'redolog_size_in_mb': 100, u'storage_type': u'FS', u'oracle_edition': u'SE', u'oracle_db_mem_totalmb': 1024, u'oracle_database_type': u'MULTIPURPOSE', u'home': u'db1', u'oracle_version_db': u'11.2.0.4'}, {'_ansible_parsed': True, 'stderr_lines': [u'grep: /u01/app/ContentsXML/inventory.xml: Aucun fichier ou dossier de ce type'], '_ansible_item_result': True, u'end': u'2017-10-22 14:33:53.525940', '_ansible_no_log': False, u'stdout': u'0', u'cmd': u'grep "/u01/app/oracle/11.2.0.4/db1" "/u01/app/ContentsXML/inventory.xml" |wc -l', u'rc': 0

**Comment by oravirt** [comment]
Hi,

I could pre-create the directory, but I don't need to. And even if I did, I'd still get the 'No such file or directory' error since none of the other directories or files exists (if this is the first install).
I'm not sure why you got the error you got, but I'm not sure it has to do with the directory not being there (as this has worked for a long time).

I just did a test 11.2.0.4 install, on a clean RHEL6.8 (and the inventory directory was not there) and it worked just fine.

TASK [oraswdb-install : Setup response file for install (DB)] *****************************************************************************************************************************************************
changed: [sifs1] => (item=[{u'is_container': True, u'oracle_db_type': u'SI', u'oracle_database_type': u'MULTIPURPOSE', u'num_pdbs': 1, u'pdb_prefix': u'orclpdb', u'oracle_db_name': u'orclcdb', u'listener_name': u'LISTENER', u'datafile_dest': u'/u01', u'redolog_size_in_mb': 100, u'state': u'present', u'oracle_edition': u'EE', u'oracle_db_mem_totalmb': 1024, u'oracle_version_db': u'11.2.0.4', u'recoveryfile_dest': u'/u01', u'oracle_db_passwd': u'Oracle123', u'home': u'db1', u'storage_type': u'FS', u'listener_port': 1521}, {'_ansible_parsed': True, 'stderr_lines': [u'grep: /u01/app/oraInventory/ContentsXML/inventory.xml: No such file or directory'], '_ansible_item_result': True, u'end': u'2017-10-22 18:57:08.398370', '_ansible_no_log': False, u'stdout': u'0', u'changed': True, u'start': u'2017-10-22 18:57:08.395357', u'delta': u'0:00:00.003013', u'cmd': u'grep "/u01/app/oracle/11.2.0.4/db1" "/u01/app/oraInventory/ContentsXML/inventory.xml" |wc -l', 'item': {u'is_container': True, u'home': u'db1', u'oracle_db_type': u'SI', u'oracle_database_type': u'MULTIPURPOSE', u'num_pdbs': 1, u'pdb_prefix': u'orclpdb', u'oracle_db_name': u'orclcdb', u'listener_name': u'LISTENER', u'datafile_dest': u'/u01', u'redolog_size_in_mb': 100, u'state': u'present', u'oracle_edition': u'EE', u'oracle_db_mem_totalmb': 1024, u'recoveryfile_dest': u'/u01', u'oracle_db_passwd': u'Oracle123', u'oracle_version_db': u'11.2.0.4', u'storage_type': u'FS', u'listener_port': 1521}, u'rc': 0, u'invocation': {u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'_raw_params': u'grep "/u01/app/oracle/11.2.0.4/db1" "/u01/app/oraInventory/ContentsXML/inventory.xml" |wc -l', u'removes': None, u'creates': None, u'chdir': None}}, 'stdout_lines': [u'0'], u'stderr': u'grep: /u01/app/oraInventory/ContentsXML/inventory.xml: No such file or directory'}])

I would probably need your group_vars/<config>, inventory and entire playbook to to try to debug it. 
Also, which Ansible version are you on?

**Comment by aetile** [comment]
Ok. My ansible version is:

 ii  ansible                                     2.4.0.0-1ppa~xenial                          all          A radically simple IT automation platform

Here's a cat of my playbook:

---

- name: Host configuration
  hosts: all
  user: vagrant
  become: yes
  strategy: debug
  roles:
     - common
     - orahost
     - oraswdb-install
     - oradb-create


Here's a cat of my test inventory:

---

all:
  hosts:
    ansible-node1:
      hostgroup: oracle
      is_sw_source_local: false
      oracle_sw_copy: true
      oracle_sw_source_www: 'http://***.***.***.***/repo/oracle/11.2.0.4'
      oracle_inventory_loc: /u01/app
      autostartup_service: true
      oracle_databases:
        - home: db1
          oracle_version_db: 11.2.0.4
          oracle_edition: SE
          oracle_db_name: test11g
          oracle_db_passwd: oracle
          oracle_db_type: SI
          storage_type: FS
          service_name: test11g
          oracle_init_params: ""
          oracle_db_mem_totalmb: 1024
          oracle_database_type: MULTIPURPOSE
          redolog_size_in_mb: 100
          listener_name: LISTENER
          state: present

Thanks for your support.

**Comment by aetile** [comment]
Hi,

After resetting my test box for investigation issue #39 I coult not reproduce this issue. The "No such file or directory message" did not make playbook execution fail anymore.
