### ISSUE TITLE
default oracle_packages for OEL7 contain weird arch

### ISSUE THREAD

**Issue by bartowl** [oravirt/ansible-oracle#411]
Problem occured on OEL7.3 with x86_86 architecture.
Somehow orahost's default package list (oracle_packages) contains multiple packages with ".i686" suffix which lead to multilib error in yum and aborted task. Do we need to name the architecture explicitely???

**Comment by Rendanic** [comment]
Hi Bartek,
as of Note _Requirements for Installing Oracle Database 19c on OL7 or RHEL7 64-bit (x86-64) (Doc ID 2551169.1):_

> Certified Operating System
> 
>     Oracle Linux 7.4
>     Red Hat Enterprise Linux 7.5

The installation of 32bit Packages should work, because we need them for 32bit client on 64bit OS. Usually this is not needed but it must work and I think the old version of Oracle Linux is the problem.

Could you upgrade the OS to Oracle Linux to >= 7.4 and test it again?
