### ISSUE TITLE
Missing requirement: libgcc 32 bits

### ISSUE THREAD

**Issue by aetile** [oravirt/ansible-oracle#43]
Hello,

Today when connecting to my test db I noticed the following:

[oracle@node1 ~]$ . oraenv
ORACLE_SID = [oracle] ? test11g
/u01/app/oracle/11.2.0.4/db1/bin/orabase: error while loading shared libraries: libgcc_s.so.1: cannot open shared object file: No such file or directory
The Oracle base has been set to 
[oracle@node1 ~]$

So I installed libgcc.i686 and the error disappeared. Also I checked Oracle doc here, it specifies this package is required before install:

https://docs.oracle.com/cd/E11882_01/install.112/e24326/toc.htm#BHCGJCEA

**Comment by aetile** [comment]
May I suggest to try the Oracle linux preinstall rpm to get rid of this kind of problems? Check here:

http://www.oracle.com/technetwork/articles/servers-storage-admin/ginnydbinstallonlinux-488779.html

You just have to add to public repo and install the package. It does rpm install, kernel and limits configuration.

**Comment by oravirt** [comment]
Fixed with https://github.com/oravirt/ansible-oracle/commit/c7cad65174f9f72502f7cfddf3899979761dd2d5

I made a deliberate decision 3.5 years ago not to use the preinstall rpm. This is supposed to work for all EL distros, and if you're running RHEL it may not be feasible or allowed to add an external Oracle repo. Also,  (at least previously) you had to hack the pre-rpm if you wanted it to work on non Oracle Linux systems because it needed kernel-uek (or something like that, I don't remember exactly)

**Comment by aetile** [comment]
Agreed. Thanks  for the update.
