### ISSUE TITLE
Add a dict of environment settings to shell and command modules

### ISSUE THREAD

**Issue by ThiloSolbrig** [oravirt/ansible-oracle#452]
* Setting CV_ASSUME_DISTID enables forward compatibility for cluvfy, gridSetup etc to run on Linux 8 and 9, also with 19.3 base release. This might obsolete the need for Gold Images here.
* On hardened systems, the system's default tempdir (e.g. /tmp) usually is noexec flagged, which denies execution of java or shell code. To make GI setup more hardening-proof, temporary directory will be changed to /u01/stage/tmp.

Implemented by: https://github.com/oravirt/ansible-oracle/pull/453

**Comment by Rendanic** [comment]
The defaults for `CV_ASSUME_DISTID ` is not working when:
- Execution of `cluvfy`
The check for RPMs is broken on OL8, when `CV_ASSUME_DISTID=OL7`, because Oracle fixed the issue in current version of `cluvfy`.
ansible-oracle does not use the `cluvfy` from CRS_HOME, due to the issues in old version of `cluvfy`.
=> Do not set `CV_ASSUME_DISTID ` during execution of `cluvfy`
=> Use the most current version of `cluvfy`.
- `gridSetup.sh -applyRU` broken on OL8 with `CV_ASSUME_DISTID=OL7`
The `opatchauto` fails with exit 2 without a usable failure in logfile for 21.6 on OL8.
Installation of 21.3 and `opatchauto` after configuration is working.

_Solution:_
Disable setting of `CV_ASSUME_DISTID` for all executables by default.
Set `CV_ASSUME_DISTID` only when really needed.

We need a rule for setting `CV_ASSUME_DISTID` for RHEL/OL, because the current default is not working in my test setups with OL8.
