### ISSUE TITLE
nr_hugepages_memory should account for a decimal value of size_in_gb_hugepages 

### ISSUE THREAD

**Issue by talek** [oravirt/ansible-oracle#488]
Hello,

Currently, `nr_hugepages_memory` is computed in `orahost` role by converting `size_in_gb_hugepages` to `int`. So, if I want to put aside 3.7G for SGA, I will get a wrong number of `nr_hugepages_memory` because I only get 3G huge pages.

I would suggest that instead of `int` filter, `float` to be used:

```
nr_hugepages_memory: |-
  {{ ((([ size_in_gb_hugepages | float, max_size_in_gb_hugepages | float ] | min | float ) * 1024**3 / hugepage_size_bytes | int)                                     
  + (oracle_nr_instances | int * 2)) | int }}
```

What do you think? Any side effects I fail to see?
Thanks!

**Comment by Rendanic** [comment]
Hi Talek,
I designed it on purpose with number of GB for Hugepages to reduce failures in sizing of HugePages.

It is simple:
SGA is 3800MB, HugePages set to 4GB. No need to think about the extra overhead. The risk of to less number of HugePages when using `use_large_pages=ONLY` is to high.

You could switch to sizing hugepages based on physical memory as an alternative solution, but that's also dangerous when decreasing the memory in the machine. That's why I added the sizing based on a fixed value.

**Comment by talek** [comment]
Hi Thorsten,

Ok, thanks for explaining the rational behind this. While I understand the risks of under-sizing the number of huge pages, the wasted allocated memory bothers me, especially on those systems where the available physical memory is not that large. Suppose you have a system with 4GB and decide to allocate 0.55% to SGA, that is 2.2G. In my case is automatically computed with the following formula:

```
sga_target: (ansible_memtotal_mb * 1024 * 1024 * 0.55) | int | round_to_granule
```

Then, the size to put aside for huge pages becomes:

```
# account for an additional 5 pages
size_in_gb_hugepages: "{{ (((oracle_databases_sga_sum | default(0)) | int)  + (5 * 2048 * 1024)) / 1024**3 }}"
```

which matches pretty well the needed huge pages size, but as a decimal number.
If I were to round up from 2.2G to 3G, I would waste a good 800M chunk which could go otherwise to PGA or OS.

Using the float approach can work I think on both cases: I can round up from 2.2G to 3G if I don't mind the wasted memory (current approach) or I can go with the precise method as described above and express `size_in_gb_hubepages` as a decimal number.

**Comment by Rendanic** [comment]
Hi Tika,
lets think about using an existing variable for your case instaed of increasing the complexity in `ansible-oracle`.
The variable [nr_hugepages](https://github.com/oravirt/ansible-oracle/tree/master/roles/orahost#nr_hugepages) is defined for internal use only, because I was planing to rename it to `_nr_hugepages`, but why not keeping it?

The `nr_hugepages` is the real value set in `sysctl.conf`. It is calculated based on other variables but you can overwrite it in your inventory to meet your requirements. That removes the maths needed to calculate the value for `size_in_gb_hugepages`which in turn is used to set `nr_hugepages` in role `orahost`.

Is that an alternative solution for you?

Kind Regards
Thorsten

**Comment by talek** [comment]
Hi Thorsten,

I've played around a bit with `nr_hugepages` variable and it's working as you described. I agree on keeping the complexity in `ansible-oracle` as manageable as posible, so as long as this variable is kept public, it covers this scenario perfectly. Thank you!

Regards,
Alec
